web/router.ex
defmodule SpinozaEx.Router do
  use SpinozaEx.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SpinozaEx do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/editions", EditionController do
      get "/fragments", FragmentController, :index
      get "/fragments/new", FragmentController, :new
      post "/fragments/create", FragmentController, :create
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SpinozaEx do
  #   pipe_through :api
  # end
end

lib/spinoza_ex/endpoint.ex
defmodule SpinozaEx.Endpoint do
  use Phoenix.Endpoint, otp_app: :spinoza_ex

  socket "/socket", SpinozaEx.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :spinoza_ex, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_spinoza_ex_key",
    signing_salt: "ZYiOXXOJ"

  plug SpinozaEx.Router
end

lib/spinoza_ex/repo.ex
defmodule SpinozaEx.Repo do
  use Ecto.Repo, otp_app: :spinoza_ex
end

web/models/edition.ex
defmodule SpinozaEx.Edition do
  use SpinozaEx.Web, :model

  schema "editions" do
    field :title, :string
    field :year, :integer
    field :editor, :string
    field :language_code, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :year, :editor, :language_code])
    |> validate_required([:title, :year, :editor, :language_code])
  end
end

web/models/fragment.ex
defmodule SpinozaEx.Fragment do
  use SpinozaEx.Web, :model

  schema "fragments" do
    field :path, :string
    field :text, :string
    belongs_to :edition, SpinozaEx.Edition

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    changeset = struct
    |> cast(params, [:path, :text, :edition_id])
    |> validate_required([:path, :text, :edition_id])
    |> validate_change(:path, &validate_path/2)
  end

  defp is_valid_fragment_path_part?(part) do
    case part do
      "aliter" -> true
      "axioma" -> true
      "definitio" -> true
      "pars" -> true
      "propositio" -> true
      "scholium" -> true
      "explanatio" -> true
      part -> match?(part, ~r/\d+/)
    end
  end

  def validate_path(:path, path) do
    starts_with_pars = String.starts_with?(path, "pars")
    fragments_are_valid = String.split(path, "/") |> Enum.all?(&is_valid_fragment_path_part?/1)
    cond do
      starts_with_pars && fragments_are_valid -> []
      starts_with_pars -> [path: "Fragments are not valid"]
      true -> [path: "Does not start with \"pars\""]
    end
  end
end

web/controllers/edition_controller.ex
defmodule SpinozaEx.EditionController do
  use SpinozaEx.Web, :controller

  alias SpinozaEx.Edition
  alias SpinozaEx.Fragment

  def index(conn, _params) do
    editions = Repo.all(Edition)
    render(conn, "index.html", editions: editions)
  end

  def new(conn, _params) do
    changeset = Edition.changeset(%Edition{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"edition" => edition_params}) do
    changeset = Edition.changeset(%Edition{}, edition_params)

    case Repo.insert(changeset) do
      {:ok, _edition} ->
        conn
        |> put_flash(:info, "Edition created successfully.")
        |> redirect(to: edition_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  defp fragments(id) do
    fragments = from f in Fragment,
      where: f.edition_id == ^id,
      select: f
  end

  def show(conn, %{"id" => id}) do
    edition = Repo.get!(Edition, id)
    render(conn, "show.html", edition: edition, fragments: fragments(id) |> Repo.all)
  end

  def edit(conn, %{"id" => id}) do
    edition = Repo.get!(Edition, id)
    changeset = Edition.changeset(edition)
    render(conn, "edit.html", edition: edition, changeset: changeset)
  end

  def update(conn, %{"id" => id, "edition" => edition_params}) do
    edition = Repo.get!(Edition, id)
    changeset = Edition.changeset(edition, edition_params)

    case Repo.update(changeset) do
      {:ok, edition} ->
        conn
        |> put_flash(:info, "Edition updated successfully.")
        |> redirect(to: edition_path(conn, :show, edition))
      {:error, changeset} ->
        render(conn, "edit.html", edition: edition, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    edition = Repo.get!(Edition, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(edition)

    conn
    |> put_flash(:info, "Edition deleted successfully.")
    |> redirect(to: edition_path(conn, :index))
  end
end

web/controllers/fragment_controller.ex
defmodule SpinozaEx.FragmentController do
  use SpinozaEx.Web, :controller
  require Logger

  alias SpinozaEx.Edition
  alias SpinozaEx.Fragment

  def edition(params) do
    @edition || Repo.get!(Edition, params["edition_id"])
  end

  def new(conn, params) do
    edition = Repo.get!(Edition, params["edition_id"])
    changeset = Fragment.changeset(%Fragment{}, %{edition_id: edition.id})
    Logger.log(:warn, inspect(changeset))
    render(conn, :new, changeset: changeset, edition: edition)
  end

  def create(conn, params) do
    %{"fragment" => fragment_params} = params
    changeset = Fragment.changeset(%Fragment{}, fragment_params)

    case Repo.insert(changeset) do
      {:ok, _fragment} ->
        conn
        |> put_flash(:info, "Thingy was successfully created")
        |> redirect(to: edition_path(conn, :edit, params["edition_id"]))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, edition: edition(params))
    end
  end
end

web/controllers/page_controller.ex
defmodule SpinozaEx.PageController do
  use SpinozaEx.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/edition_view.ex
defmodule SpinozaEx.EditionView do
  use SpinozaEx.Web, :view
end

web/views/error_view.ex
defmodule SpinozaEx.ErrorView do
  use SpinozaEx.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/fragment_view.ex
defmodule SpinozaEx.FragmentView do
  use SpinozaEx.Web, :view
end

web/views/layout_view.ex
defmodule SpinozaEx.LayoutView do
  use SpinozaEx.Web, :view
end

web/views/page_view.ex
defmodule SpinozaEx.PageView do
  use SpinozaEx.Web, :view
end

web/templates/edition/edit.html.eex
<h2>Edit edition</h2>

<%= render "form.html", changeset: @changeset,
                        action: edition_path(@conn, :update, @edition) %>

<%= link "Back", to: edition_path(@conn, :index) %>

web/templates/edition/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :year, class: "control-label" %>
    <%= number_input f, :year, class: "form-control" %>
    <%= error_tag f, :year %>
  </div>

  <div class="form-group">
    <%= label f, :editor, class: "control-label" %>
    <%= text_input f, :editor, class: "form-control" %>
    <%= error_tag f, :editor %>
  </div>

  <div class="form-group">
    <%= label f, :language_code, class: "control-label" %>
    <%= text_input f, :language_code, class: "form-control" %>
    <%= error_tag f, :language_code %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/edition/index.html.eex
<h2>Listing editions</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Editor</th>
      <th>Language code</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for edition <- @editions do %>
    <tr>
      <td><%= edition.title %></td>
      <td><%= edition.year %></td>
      <td><%= edition.editor %></td>
      <td><%= edition.language_code %></td>

      <td class="text-right">
        <%= link "Show", to: edition_path(@conn, :show, edition), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: edition_path(@conn, :edit, edition), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: edition_path(@conn, :delete, edition), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New edition", to: edition_path(@conn, :new) %>

web/templates/edition/new.html.eex
<h2>New edition</h2>

<%= render "form.html", changeset: @changeset,
                        action: edition_path(@conn, :create) %>

<%= link "Back", to: edition_path(@conn, :index) %>

web/templates/edition/show.html.eex
<h2>Show edition</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @edition.title %>
  </li>

  <li>
    <strong>Year:</strong>
    <%= @edition.year %>
  </li>

  <li>
    <strong>Editor:</strong>
    <%= @edition.editor %>
  </li>

  <li>
    <strong>Language code:</strong>
    <%= @edition.language_code %>
  </li>

</ul>

<div>
  <%= link "Create fragment", to: edition_fragment_path(@conn, :new, @edition) %>
</div>

<ul>
<%= for fragment <- @fragments do %>
  <li>
    <%= inspect(fragment) %>
  </li>
<% end %>
</ul>

<%= link "Edit", to: edition_path(@conn, :edit, @edition) %>
<%= link "Back", to: edition_path(@conn, :index) %>

web/templates/fragment/new.html.eex
<div>
  Fragment for edition <%= inspect(@edition.title) %>
  <%= form_for @changeset, edition_fragment_path(@conn, :create, @edition), fn f -> %>
    <%= inspect(@changeset) %>
    <div class="form-group">
      <%= label f, :path %>
      <%= text_input f, :path %>
      <%= error_tag f, :path %>
    </div>
    <div class="form-group">
      <%= label f, :text %>
      <%= text_input f, :text %>
      <%= error_tag f, :text %>
    </div>

    <%= hidden_input f, :edition_id %>

    <%= submit "Submit" %>
  <% end %>
</div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello SpinozaEx!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>